// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3oCpN2FSPc4KsOoBlZ1KXG7LtGPB3_5Y',
    appId: '1:280499853345:web:4fbb64bf2db149efc76b60',
    messagingSenderId: '280499853345',
    projectId: 'lamp-ce83c',
    authDomain: 'lamp-ce83c.firebaseapp.com',
    storageBucket: 'lamp-ce83c.appspot.com',
    measurementId: 'G-01NEXF0TD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9gzV7HQiPA-qwoAurvnAWWfzbR8xA6NU',
    appId: '1:280499853345:android:1ecac17155eaee68c76b60',
    messagingSenderId: '280499853345',
    projectId: 'lamp-ce83c',
    storageBucket: 'lamp-ce83c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqUvQcn4Tj_o_0Dkxb-oTE74wL71K5Vcs',
    appId: '1:280499853345:ios:a1bf8252ba1e9c66c76b60',
    messagingSenderId: '280499853345',
    projectId: 'lamp-ce83c',
    storageBucket: 'lamp-ce83c.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
